name: BedWarsProxy
version: 1.0-SNAPSHOT
description: Arena connecter for BedWars1058
main: com.andrei1058.bedwars.proxy.BedWarsProxy
author: andrei1058
api-version: '1.13'
softdepend:
  - Commons
  - Parties
  - Lobby
  - Partys